name: auto-assign
on:
  pull_request:
    types: [opened,ready_for_review ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: .github/auto-assign.yml